include(
    ":mobile-app",
    ":things-app",
    ":shared-interfaces",
    ":architecture-sdk",
    ":core",
    ":extensions-android",
    ":extensions-kotlin",
    ":splash-feature",
    ":login-feature"
)
