# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Lint everything"
  lane :lint do
    gradle(task: "lintDebug")
  end

  desc "Build debug things app"
  lane :buildThings do
    gradle(task: ":Things:assembleDebug")
  end

  desc "Build debug mobile app"
  lane :buildMobile do
    gradle(task: ":Mobile:assembleDebug")
  end

  desc "Runs CI Workflow"
  lane :ci do
    buildThings
    buildMobile
    test
  end  

end