internal object Versions {

    // BuildPlugins
    const val kotlin = "1.3.72"
    const val androidBuildTools = "4.0.0-beta04"
    const val googleServices = "4.3.3"
    const val fabric = "1.31.2"
    const val ktlint = "9.2.1"
    const val versions = "0.28.0"

    const val coroutines = "1.3.5"
    const val arrow = "0.9.0"
    const val constraintLayout = "2.0.0-beta4"
    const val appCompat = "1.2.0-beta01"
    const val things = "1.0"
    const val lifecycle = "2.3.0-alpha01"
    const val lifecycleTest = "2.1.0"
    const val koin = "2.1.5"
    const val firebaseCore = "17.0.1"
    const val firebaseCommon = "18.0.0"
    const val firebaseCrashlytics = "2.10.1"
    const val firebaseFirestone = "19.0.2"
    const val room = "2.2.5"
    const val jackson = "2.9.9"
    const val junit = "1.1.1"
    const val espresso = "3.2.0"
    const val runner = "1.2.0"
    const val mockk = "1.9.3.kotlin12"
    const val kotlinTest = "3.4.2"
    const val robolectric = "4.3.1"
    const val logger = "2.2.0"
}